package com.sherina.mammalsclassification

object MammalsData {

    private val mammalsPhoto = arrayOf(
        R.drawable.britishshorthair,
        R.drawable.bengal,
        R.drawable.persian,
        R.drawable.ragdoll,
        R.drawable.sphynx
    )
    private val mammalsName = arrayOf(
        "British Shorthair",
        "Bengal",
        "Persian",
        "Ragdoll",
        "Sphynx"
    )

    private val mammalsInformation = arrayOf(
        "British Shorthair adalah versi ras kucing domestik tradisional Inggris, dengan tubuh kekar, bulu lebat, dan wajah lebar. Varian warna yang paling dikenal adalah \"British Blue\", dengan bulu biru keabu-abuan, mata oranye, dan ekor berukuran sedang. Trah ini juga telah dikembangkan dalam berbagai warna dan pola lain, termasuk tabby dan colourpoint.\n" +
                "\n" +
                "Ini adalah salah satu ras kucing paling kuno yang diketahui. Di zaman modern, kucing ini tetap menjadi ras kucing yang paling populer di negara asalnya, seperti yang didaftarkan oleh Governing Council of the Cat Fancy (GCCF) di Inggris. Seperempat dari semua anak kucing yang terdaftar di GCCF setiap tahun adalah British Shorthairs, menjadikan kucing British sebagai kucing silsilah paling populer di Inggris.\n" +
                "\n" +
                "British Shorthair adalah kucing besar yang tampak relatif kuat, memiliki dada lebar, kaki kuat dan tebal dengan cakar membulat, serta ekor berukuran sedang dan berujung tumpul. Kepalanya relatif besar dan bulat, dengan moncong pendek, pipi lebar (paling terlihat pada jantan dewasa, yang cenderung memiliki rahang menonjol) dan mata bulat besar berwarna oranye tembaga tua dalam warna Biru Inggris dan warnanya bervariasi tergantung pada mantel. Telinganya yang besar lebar dan lebar.\n" +
                "\n" +
                "Varian British Blue sering disalahartikan dengan Scottish Fold abu-abu, ras yang berkerabat dekat dengan British Shorthair. Namun, ciri khas Shorthair adalah memiliki telinga segitiga yang lancip, sedangkan Fold memiliki telinga yang lebih lembut dan terlipat. Dibandingkan dengan kebanyakan ras kucing, mereka lambat dalam mencapai kedewasaan, mencapai perkembangan fisik penuh pada usia sekitar tiga tahun. Tidak seperti biasanya di antara kucing domestik, mereka adalah ras dimorfik seksual, dengan jantan rata-rata memiliki berat 9–17 lb (4,1–7,7 kg) dan betina 7–12 lb (3,2–5,4 kg).\n" +
                "\n" +
                "Bulu British Shorthair adalah salah satu ciri khas ras ini. Ia sangat padat tetapi tidak memiliki lapisan bawah; oleh karena itu, teksturnya lebih mewah daripada berbulu atau halus, dengan tumpukan yang kuat dan \"renyah\" yang terlihat jelas di seluruh tubuh kucing saat ia bergerak. Meskipun British Blue tetap menjadi varian yang paling dikenal, British Shorthairs telah dikembangkan dalam banyak warna dan pola lain. Hitam, biru, putih, merah, krem, perak, emas dan—yang terbaru—kayu manis dan coklat kekuningan diterima menurut semua standar resmi, baik dalam pola solid atau colourpoint, tabby, shaded, dan bicolour. Warna hidung British Shorthair: hitam, merah ceri, merah bata; lingkaran garis hidung hitam di pinggirannya.\n" +
                "\n" +
                "Mereka adalah ras yang santai dan bermartabat, tidak aktif dan suka bermain seperti kebanyakan anjing lainnya, tetapi memiliki sifat manis dan setia kepada pemiliknya, menjadikan mereka favorit para pelatih hewan. Mereka cenderung aman berada di dekat hewan peliharaan lain dan anak-anak karena mereka menoleransi cukup banyak interaksi fisik, tetapi biasanya tidak suka digendong atau digendong. Mereka hanya memerlukan sedikit perawatan dan dapat dipelihara dengan baik sebagai kucing yang hanya dipelihara di dalam ruangan; Namun, mereka rentan terhadap obesitas kecuali pola makan mereka diperhatikan. Mereka pendiam dan waspada, tetapi jika mereka mempercayai pemiliknya, mereka akan diam-diam mengikuti aktivitas pemiliknya dan tinggal bersama mereka. Kucing British Shorthair bukanlah kucing pangkuan. Mereka lebih terbiasa berada di samping orang dibandingkan jongkok di pangkuan orang. Demikian pula, mereka lebih menyukai perasaan menginjak tanah. Mereka memiliki suara rendah dan tingkat aktivitas sedang. Ketika tidak ada orang di rumah, mereka akan diam di rumah dan menunggu pemiliknya kembali.\n" +
                "\n" +
                "Komite ras Inggris menganggap British Shorthair sebagai kucing berumur panjang, dengan harapan hidup 14-20 tahun. Data klinik dokter hewan dari Inggris menunjukkan umur rata-rata 11,8 tahun. Data asuransi Swedia menyebutkan umur rata-rata ras ini > 12,5 tahun. 82% British Shorthair hidup hingga 10 tahun atau lebih dan 54% hidup hingga 12,5 tahun atau lebih. Kardiomiopati hipertrofik (HCM) bisa menjadi masalah pada ras ini. Sebuah studi prevalensi di Denmark dengan lebih dari 329 kucing menunjukkan bahwa 20,4% jantan dan 2,1% betina menderita HCM. Selain itu, 6,4% laki-laki dan 3,5% perempuan dinilai ragu-ragu.",
        "Kucing Bengal adalah ras kucing peliharaan yang dihasilkan dari persilangan kucing domestik, khususnya Mau Mesir tutul, dengan kucing macan tutul Asia (Prionailurus bengalensis). Nama rasnya berasal dari nama taksonomi kucing macan tutul.\n" +
                "\n" +
                "Burung Bengal mempunyai penampilan yang liar; kilau emasnya berasal dari nenek moyang kucing macan tutul, dan bulunya mungkin menunjukkan bintik-bintik, mawar, tanda mata panah, atau marmer. Mereka adalah ras energik yang membutuhkan banyak latihan dan permainan.\n" +
                "\n" +
                "Benggala hadir dalam berbagai warna bulu. Mengenali beberapa warna Bengal. Brown Spotted, Seal Lynx Point (salju), Sepia, silver, dan Mink Spotted Tabby Bengals.\n" +
                "\n" +
                "Anak kucing Bengal salju bermata biru arang di tempat tidur mengulurkan tangan untuk menyelidiki kamera Kucing Bengal adalah satu-satunya ras kucing domestik yang memiliki tanda roset.\n" +
                "\n" +
                "Orang paling sering mengasosiasikan Bengal dengan warna paling populer: Bengal berbintik coklat/berwarna merah jambu. Namun, Bengal memiliki corak dan warna yang sangat beragam. Bahkan dalam kategori Bintik Coklat/Roset, Bengal dapat memiliki warna: merah, coklat, hitam, centang, abu-abu, tutul, roset, mendung. Banyak orang yang terkesima dengan kemiripan Kucing Bengal dengan macan tutul. Di antara kucing domestik, tanda Bengal mungkin yang paling bervariasi dan unik.\n" +
                "\n" +
                "Kucing Bengal dengan bulu roset yang besar dan warna yang sangat kontras disebut sebagai “clouded bengal”. Kucing domestik memiliki empat pola bulu yang berbeda dan dapat diwariskan – ticked, mackerel, blotched, dan tutul – yang secara kolektif disebut sebagai tanda tabby. Christopher Kaelin, ahli genetika Universitas Stanford, telah melakukan penelitian yang digunakan untuk mengidentifikasi gen tutul dan gen marmer pada kucing Bengal domestik. Kaelin mempelajari variasi warna dan pola kucing liar di California Utara, dan mampu mengidentifikasi gen yang bertanggung jawab atas pola marmer pada kucing Bengal.\n" +
                "\n" +
                "Bengal adalah ras kucing tutul berukuran sedang hingga besar. Bengali panjang dan ramping. Kucing Bengal lebih besar dari rata-rata kucing rumahan karena tubuhnya yang berotot. Para peternak dalam beberapa tahun terakhir telah memulai pembiakan selektif untuk membiakkan kucing Bengal yang ukurannya mendekati kucing macan tutul Asia asli. Kucing Bengal cerdas, energik, dan suka bermain (meskipun dalam beberapa kasus yang jarang terjadi, mereka mungkin sangat malas). Banyak pemilik Bengal mengatakan bahwa Bengal mereka secara alami mengambil barang, dan mereka sering menikmati bermain air. Kardiomiopati hipertrofik (HCM) merupakan masalah utama pada ras kucing Bengal. Ini adalah penyakit di mana otot jantung (miokardium) menjadi tebal secara tidak normal (hipertrofi). Otot jantung yang tebal dapat mempersulit jantung kucing dalam memompa darah. Satu-satunya cara untuk menentukan kesesuaian kucing Bengal untuk diternakkan adalah dengan memeriksakan jantung kucing tersebut ke dokter ahli jantung.",
        "Kucing persia merupakan salah satu ras kucing berbulu panjang yang memiliki ciri wajah bulat dan moncong pendek. Ia juga dikenal sebagai \"Persian Longhair\" di negara-negara berbahasa Inggris. Nenek moyang kucing Persia pertama yang terdokumentasi diimpor ke Italia dari Persia sekitar tahun 1620. Dikenal luas oleh pecinta kucing sejak akhir abad ke-19, kucing Persia pertama kali diadopsi oleh Inggris, dan kemudian terutama oleh peternak Amerika setelah Perang Dunia II. Standar ras beberapa organisasi pecinta kucing menganggap Himalayan dan Exotic Shorthair sebagai varian dari ras ini, sementara yang lain memperlakukan mereka sebagai ras terpisah.\n" +
                "\n" +
                "Pembiakan selektif yang dilakukan oleh para peternak telah memungkinkan berkembangnya berbagai macam warna bulu, namun juga menyebabkan semakin banyak terciptanya kucing Persia bermuka datar. Disukai oleh para peternak, struktur kepala ini dapat membawa sejumlah masalah kesehatan. Seperti halnya ras siam, ada upaya dari beberapa peternak untuk melestarikan jenis kucing tua, ras tradisional, yang memiliki moncong lebih menonjol, sehingga lebih populer di kalangan masyarakat umum. Penyakit ginjal polikistik herediter umum terjadi pada ras ini dan menyerang hampir separuh populasi di beberapa negara.\n" +
                "\n" +
                "Pada tahun 2021, kucing Persia menduduki peringkat keempat ras kucing terpopuler di dunia menurut Cat Fanciers' Association, sebuah lembaga pencatatan kucing nirlaba di Amerika. Mantel Persia terdiri dari lapisan bawah berbulu dan lapisan luar berbulu panjang. Mantel kehilangan semua lapisan bawah wol yang tebal di musim panas, dan hanya rambut panjang yang tersisa. Rambut di bahu dan kaki belakang bagian atas agak lebih pendek.\n" +
                "\n" +
                "Kucing Persia gaya pertunjukan memiliki bulu yang sangat panjang dan tebal, kaki pendek, kepala lebar dengan telinga berjauhan, mata besar, dan moncong sangat pendek. Trah ini awalnya memiliki moncong pendek, tetapi seiring berjalannya waktu, karakteristik ini menjadi sangat berlebihan, khususnya di Amerika Utara. Kucing Persia dapat memiliki hampir semua warna atau corak.\n" +
                "\n" +
                "Kucing Persia umumnya digambarkan sebagai kucing yang pendiam. Biasanya bersifat tenang, ia beradaptasi dengan baik dengan kehidupan apartemen. Orang Himalaya cenderung lebih aktif karena pengaruh sifat-sifat Siam. Dalam sebuah penelitian yang membandingkan persepsi pemilik kucing terhadap kucingnya, kucing Persia dinilai lebih tinggi dibandingkan kucing non-silsilah dalam hal kedekatan dan kasih sayang kepada pemiliknya, keramahan terhadap orang asing, kebersihan, prediktabilitas, vokalisasi, dan kerewelan terhadap makanan.\n" +
                "\n" +
                "Data asuransi hewan peliharaan dari Swedia menyebutkan umur rata-rata kucing dari kelompok Persia (Persia, Chinchilla, Himalayan, dan Exotic) hanya di atas 12,5 tahun, sementara sebagian besar kucing hidup hingga mereka berusia sekitar 15 tahun. 76% dari kelompok ini hidup sampai 10 tahun atau lebih dan 52% hidup sampai 12,5 tahun atau lebih. Data klinik hewan dari Inggris menunjukkan umur rata-rata 12–17 tahun, dengan median 14,1.\n" +
                "\n" +
                "Orang Persia brachycephalic modern memiliki tengkorak bulat besar serta wajah dan hidung yang pendek. Konformasi wajah ini membuat ras ini rentan terhadap kesulitan bernapas, masalah kulit dan mata, serta kesulitan melahirkan. Kelainan anatomi yang berhubungan dengan ras brachycephalic dapat menyebabkan sesak napas. Saluran air mata yang cacat menyebabkan epifora, luapan air mata ke wajah, yang umum terjadi tetapi terutama hanya bersifat kosmetik. Entropion, lipatan kelopak mata ke dalam, menyebabkan bulu mata bergesekan dengan kornea, dan dapat menyebabkan robekan, nyeri, infeksi, dan kerusakan kornea. Kondisi ini umum terjadi pada orang Persia, dan biasanya mengenai bagian medial kelopak mata bawah. Demikian pula pada trikiasis kelopak mata atas atau trikiasis lipatan hidung, bulu mata/rambut dari kelopak mata dan rambut dari lipatan hidung dekat mata tumbuh sedemikian rupa hingga bergesekan dengan kornea. Distosia, suatu persalinan yang tidak normal atau sulit, relatif umum terjadi pada orang Persia. Akibatnya, angka kelahiran mati lebih tinggi dari biasanya, berkisar antara 16,1% hingga 22,1%, dan sebuah penelitian pada tahun 1973 menyebutkan angka kematian anak kucing (termasuk bayi lahir mati) sebesar 29,2%. Sebuah penelitian kedokteran hewan pada tahun 2010 mendokumentasikan masalah kesehatan serius yang disebabkan oleh kepala brachycephalic.",
        "Ragdoll adalah ras kucing dengan bulu berwarna dan mata biru. Morfologinya besar dan berotot, serta memiliki bulu setengah panjang dan lembut seperti sutra. Ragdolls dikembangkan oleh peternak Amerika Ann Baker pada tahun 1960an. Mereka terkenal karena temperamennya yang patuh dan tenang, serta sifatnya yang penuh kasih sayang. Nama 'Ragdoll' diambil dari kecenderungan individu dari induk asli untuk menjadi lemas dan santai saat diangkat.\n" +
                "\n" +
                "Ras ini sangat populer di Inggris dan negara asal ras ini di Amerika Serikat dan sering dikenal sebagai 'kucing mirip anjing' atau 'kucing mirip anak anjing'. Moniker ini disebabkan oleh kecenderungannya untuk mengikuti orang lain, kenyamanan jika ditangani secara fisik, dan relatif kurangnya agresivitas terhadap hewan peliharaan lainnya. Ragdoll adalah kucing kuat, besar, dan berat yang dapat dibedakan dengan tanda berbentuk V terbalik di dahi, mata biru bulat besar, bulu lembut dan tebal, anggota badan tebal, ekor panjang, dan tubuh lembut. Cincin warna mereka biasanya tiga warna atau dua warna.\n" +
                "\n" +
                "Ragdoll dikenal memiliki sifat yang sangat lemah dan tenang, dengan klaim bahwa karakteristik ini diturunkan dari ras Persia dan Birman. Terdapat beragam pendapat mengenai apakah sifat ini mungkin merupakan hasil mutasi genetik atau sekadar reaksi naluri saat dipungut oleh induknya saat masih anak kucing. Kepatuhan ekstrim dari beberapa individu telah menimbulkan mitos bahwa Ragdolls tahan rasa sakit. Beberapa peternak di Inggris telah mencoba untuk menghindari kucing yang pincang karena kekhawatiran bahwa kepatuhan yang ekstrim 'mungkin bukan yang terbaik bagi kucingnya'.\n" +
                "\n" +
                "Materi pemasaran dan publisitas standar ras menggambarkan Ragdoll sebagai kucing yang penuh kasih sayang, cerdas, temperamennya santai, lembut, dan kucing pangkuan yang mudah ditangani. Hewan ini sering dikenal sebagai 'anak anjing', 'kucing mirip anjing', 'anjing kucing', dll., karena sifatnya yang tenang dan perilakunya yang penuh kasih sayang, kucing sering mengikuti pemiliknya dari kamar ke kamar serta mencari. kasih sayang fisik yang mirip dengan ras anjing tertentu. Ragdoll dapat dilatih untuk mengambil mainan dan senang melakukannya. Mereka memiliki sifat yang sangat menyenangkan yang sering kali bertahan hingga usia lanjut. Tidak seperti banyak ras lainnya, Ragdoll lebih suka tinggal di tempat yang rendah daripada di titik tertinggi dalam rumah.\n" +
                "\n" +
                "Ragdoll adalah salah satu ras kucing peliharaan terbesar. Betina dewasa memiliki berat 8 hingga 15 pon (3,6 hingga 6,8 kg). Jantan jauh lebih besar, berkisar antara 12 hingga 20 pon (5,4 hingga 9,1 kg) atau lebih. Ragdoll memerlukan waktu hingga empat tahun untuk mencapai ukuran dewasa. Mereka memiliki tubuh kokoh, kerangka besar, dan kaki proporsional. Kepala mereka lebar dengan bagian atas rata dan ruang lebar di antara telinga. Mereka memiliki tubuh yang panjang dan berotot dengan dada lebar dan leher pendek. Ekornya lebat dan panjang, cakarnya besar, bulat, dan berumbai, serta bulunya halus, padat, dan panjangnya sedang hingga panjang. Karena bulunya yang cenderung panjang, mereka biasanya perlu disikat setidaknya dua kali seminggu. Orang dewasa mengembangkan celana dalam di kaki belakangnya dan leher di lehernya.\n" +
                "\n" +
                "Trah ini sering dikenal karena matanya yang besar, bulat, dan berwarna biru tua. Meskipun trah ini dikenal memiliki mata biru, ini bukanlah ciri eksklusif Ragdoll. Gen pewarnaan titik juga bertanggung jawab atas mata biru yang khas ini. Nuansa biru yang lebih pekat disukai dalam pertunjukan kucing. Kucing ragdoll jantan dengan mata biru. Kucing Ragdoll dapat memiliki mata biru bulat besar yang khas. Meskipun trah ini memiliki bulu yang mewah, sebagian besar terdiri dari bulu pelindung yang panjang, sedangkan kurangnya lapisan bawah yang padat, menurut Asosiasi Pemelihara Kucing, menghasilkan 'pengurangan kerontokan dan anyaman'. Namun mungkin ada peningkatan jumlah kerontokan yang nyata di musim semi. Ragdoll tersedia dalam enam warna berbeda: merah, segel, coklat dan 'encer' yang sesuai, termasuk biru, ungu, dan krem. Ini juga termasuk variasi lynx dan kulit penyu dalam semua warna dan tiga pola. Anak kucing Ragdoll dilahirkan dengan warna putih; mereka memiliki warna yang bagus pada usia 8–10 minggu dan penuh warna serta bulu pada usia 3–4 tahun. Tiga pola berbeda tersebut adalah: Colorpoint – Satu warna yang menggelap di bagian ekstremitas (hidung, telinga, ekor, dan cakar). Mitted – Sama seperti runcing tetapi dengan cakar dan perut berwarna putih. Dengan atau tanpa kobaran api (garis atau bintik putih di wajah), mereka harus memiliki 'belly stripe' (garis putih yang membentang dari dagu hingga alat kelamin) dan dagu berwarna putih. Mitted Ragdolls, yang tidak diizinkan diberi judul di CFA hingga musim pertunjukan 2008-2009, sering disalahartikan dengan Birman. Cara termudah untuk membedakannya adalah berdasarkan ukuran (Ragdoll lebih besar) dan warna dagu (Mitted Ragdoll memiliki dagu berwarna putih, sedangkan Birman memiliki dagu berwarna), meskipun peternak mengenali keduanya berdasarkan bentuk kepala dan tulangnya.\n" +
                "\n" +
                "Dua warna – Kaki berwarna putih, huruf V terbalik putih di wajah, perut putih, dan terkadang bercak putih di punggung (warna putih dalam jumlah berlebihan, atau 'putih tinggi', pada dua warna dikenal sebagai pola Van, meskipun hal ini tidak terjadi hampir sama. Sebuah studi yang memanfaatkan data asuransi Swedia menunjukkan bahwa di antara ras kucing pada umumnya, ras Ragdoll dan Siam memiliki tingkat kelangsungan hidup paling rendah. Mereka biasanya hidup antara 12 hingga 15 tahun. Kardiomiopati hipertrofik (HCM) adalah penyakit jantung yang umum terjadi pada semua kucing dan paling sering disebabkan oleh genetik. Penyakit ini menyebabkan penebalan dinding jantung, sehingga membuat jantung memompa darah menjadi kurang efisien. Dalam beberapa kasus, penyakit ini dapat menyebabkan kematian mendadak. Pada Ragdoll yang homozigot positif mengidap penyakit ini (memiliki dua salinan (gen HCM), kondisi ini dapat muncul sejak dini (semuda enam bulan) dan cenderung parah, dengan sebagian besar kucing meninggal pada usia 3 tahun. Kucing heterozigot (satu salinan gen HCM) cenderung memiliki gejala yang lebih lambat dan perkembangan penyakit yang lebih lambat. penyakit, dengan dampak yang tidak terlalu parah.\n" +
                "\n" +
                "Frekuensi alel mutasi Ragdoll HCM R820W adalah 0,17 pada kucing asal Italia dan 0,23 pada kucing asal AS pada tahun 2013. Referensi ini menyatakan bahwa prevalensi R820W adalah 30% di Inggris. Prevalensi HCM ditemukan sebesar 2,9% (95% CI = 2,7–8,6%) dalam penelitian ini.",
        "Kucing Sphynx, juga dikenal sebagai Sphynx Kanada, adalah jenis kucing yang dikenal tidak memiliki bulu. Kucing yang tidak berbulu adalah mutasi genetik yang terjadi secara alami, dan Sphynx dikembangkan melalui pembiakan selektif hewan-hewan ini, dimulai pada tahun 1960-an. Menurut standar ras, kulitnya harus memiliki tekstur kulit chamois, karena memiliki bulu yang halus, atau kucing mungkin tidak berbulu sama sekali. Kumis mungkin ada, utuh atau patah, atau mungkin tidak ada sama sekali. Kucing ini memiliki kepala yang sempit dan panjang serta kaki berselaput. Kulit mereka sama dengan warna bulu mereka, dan semua tanda kucing yang biasa (solid, point, van, tabby, tortie, dll.) dapat ditemukan pada kulit kucing Sphynx. Karena tidak memiliki bulu, kucing Sphynx lebih mudah kehilangan panas tubuh dibandingkan kucing berbulu halus, sehingga membuatnya hangat saat disentuh dan cenderung mencari tempat hangat.\n" +
                "\n" +
                "Standar ras ini ditentukan oleh The International Cat Association (TICA): Kepala berbentuk baji dengan tulang pipi menonjol, Mata besar berbentuk lemon, Telinga sangat besar dengan bulu di bagian dalam, namun lembut di bagian luar, Leher berotot dan kuat. dengan panjang sedang, badan dengan panjang sedang, dada seperti tong, dan perut bulat dan penuh, terkadang disebut perut buncit, Bantalan kaki lebih tebal dibandingkan kucing lain, memberi kesan seperti berjalan di atas bantalan, Seperti cambuk, ekor meruncing dari badan hingga ujung, (terkadang dengan bulu di seluruh ekor atau segumpal bulu di ujungnya, seperti singa), Tubuhnya berotot\n" +
                "\n" +
                "Sphynx dikenal karena perilaku ekstrovertnya. Mereka menunjukkan energi, kecerdasan, rasa ingin tahu, dan kasih sayang tingkat tinggi kepada pemiliknya. Mereka adalah salah satu ras kucing yang lebih mirip anjing, sering menyapa pemiliknya di depan pintu dan ramah saat bertemu orang asing. Sphynx menghadapi tantangan karena kurangnya bulu pelindung. Kanker kulit bisa menjadi masalah jika terkena sinar matahari dalam jangka waktu lama. Kurangnya bulu dapat menyebabkan masalah kesehatan pada anak kucing di minggu-minggu pertama kehidupannya karena rentan terhadap infeksi saluran pernapasan. Peternak yang memiliki reputasi baik tidak boleh membiarkan anak kucingnya pindah ke rumah baru sebelum berusia minimal 14 minggu untuk memastikan anak kucing tersebut cukup dewasa untuk beradaptasi di lingkungan baru.\n" +
                "\n" +
                "Trah ini memang memiliki kelainan genetik kardiomiopati hipertrofik (HCM). Ras kucing domestik lainnya yang rentan terhadap HCM termasuk kucing Persia, Ragdoll, kucing Hutan Norwegia, kucing Siberia, British Shorthair, dan Maine Coon; namun, kucing domestik apa pun termasuk ras campuran dapat tertular HCM. Penelitian sedang dilakukan untuk memahami hubungan antara pembiakan dan kelainan ini. Kucing disaring untuk penyakit HCM dengan ekokardiografi (USG jantung), serta tes tambahan yang ditentukan oleh ahli jantung hewan termasuk elektrokardiogram (EKG, EKG), rontgen dada (rontgen), dan/atau tes darah.\n" +
                "\n" +
                "Kucing Sphynx memiliki tingkat penyakit jantung yang tinggi, baik berupa HCM maupun displasia katup mitral. Dalam penelitian tahun 2012 terhadap 114 kucing Sphynx, 34% ditemukan memiliki kelainan jantung, dengan 16 kucing mengalami displasia katup mitral dan 23 kucing menderita HCM. Prevalensi ini ditemukan pada kucing dengan usia rata-rata 2,62 tahun. Kucing jantan menderita penyakit yang lebih parah dibandingkan kucing betina dan sering kali mengidapnya lebih awal, yaitu pada usia rata-rata 19 bulan untuk jantan dan 29 bulan untuk betina. Karena prevalensi penyakit jantung genetik yang tinggi pada ras ini, banyak peternak yang akan merekomendasikan skrining HCM. tahunan.\n" +
                "\n" +
                "Sindrom miastenia kongenital (CMS), yang sebelumnya disebut sebagai distrofi otot, miopati, atau spastisitas, adalah jenis kelainan neuromuskular bawaan yang terkait dengan defisiensi alfa-distroglikan, ditemukan pada kucing Sphynx dan Devon Rex serta varian dari ras ini, yang dapat terjadi antara 3 hingga 23 minggu pertama kehidupan mereka. Kondisi ini juga pernah dijelaskan, namun jarang terlihat. Kucing yang terkena CMS menunjukkan kelemahan dan kelelahan otot secara umum, serta ventrofleksi kepala dan leher, kepala terayun-ayun, dan penonjolan tulang belikat."
    )

    val listMammals: ArrayList<Mammals>
        get() {
            val list = arrayListOf<Mammals>()
            for (position in mammalsName.indices) {
                val mammals = Mammals()
                mammals.mammalsPhoto = mammalsPhoto[position]
                mammals.mammalsName = mammalsName[position]
                mammals.mammalsInformation = mammalsInformation[position]
                list.add(mammals)
            }
            return list

        }
}